# Generated by Django 4.2.3 on 2023-07-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('payment_amount', models.IntegerField()),
                ('legal_entity', models.BooleanField(default=False)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('spent_money', models.IntegerField()),
                ('status', models.CharField(choices=[('new', 'new'), ('on_moderation', 'on_moderation'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], max_length=20)),
                ('payment_type', models.CharField(choices=[('cash', 'cash'), ('money_transfer', 'money_transfer')], default='cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('education_type', models.CharField(choices=[('bachelor', 'bachelor'), ('master', 'master')], max_length=20)),
                ('contract_fee', models.IntegerField()),
                ('allocated_money', models.IntegerField()),
                ('sponsors', models.ManyToManyField(related_name='students', to='app.sponsor')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.university')),
            ],
        ),
    ]
