# Generated by Django 4.2.3 on 2023-07-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'cash'), ('money_transfer', 'money_transfer')], default='money_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='spent_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('on_moderation', 'on_moderation'), ('confirmed', 'confirmed'), ('cancelled', 'cancelled')], default='new', max_length=20),
        ),
    ]
