# Generated by Django 4.2.3 on 2023-07-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_test_alter_sponsor_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='asd',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
