# Generated by Django 4.2.3 on 2023-07-27 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_test_asd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('asd', models.CharField(blank=True, default='test-default', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='asd',
            field=models.CharField(blank=True, default='test-default', max_length=255),
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.test')),
                ('test2', models.ManyToManyField(to='app.test2')),
            ],
        ),
    ]
