# Generated by Django 4.2.3 on 2023-07-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_status_sponsor_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b',
            name='name',
        ),
        migrations.RemoveField(
            model_name='b',
            name='test',
        ),
        migrations.RemoveField(
            model_name='b',
            name='test2',
        ),
    ]
