# Generated by Django 4.2.3 on 2023-07-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_b_name_remove_b_test_remove_b_test2'),
    ]

    operations = [
        migrations.AddField(
            model_name='b',
            name='name2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='b',
            name='name3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b',
            name='name4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='b',
            name='noname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.test'),
        ),
        migrations.AddField(
            model_name='b',
            name='test2',
            field=models.ManyToManyField(to='app.test2'),
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(blank=True, max_length=255)),
                ('name3', models.CharField(blank=True, max_length=255, null=True)),
                ('name4', models.CharField(default='', max_length=255)),
                ('noname', models.CharField(max_length=255)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.test')),
                ('test2', models.ManyToManyField(to='app.test2')),
            ],
        ),
    ]
