# Generated by Django 4.2.3 on 2023-08-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_shit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allocated_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsors',
            field=models.ManyToManyField(null=True, related_name='students', to='app.sponsor'),
        ),
        migrations.CreateModel(
            name='SponsorByStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_money', models.IntegerField()),
                ('sponsor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sponsor')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student')),
            ],
        ),
    ]
