# Generated by Django 4.2.3 on 2023-08-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_student_created_at_alter_sponsor_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
